"""add_assigned_department

Revision ID: 86a8d2c82fca
Revises: f5024d8a921f
Create Date: 2026-09-16 15:22:05.219917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a8d2c82fca'
down_revision: Union[str, Sequence[str], None] = 'f5024d8a921f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('assigned_department', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'assigned_department')
    # ### end Alembic commands ###
