"""add_user_department

Revision ID: b2f56c8c8e86
Revises: 86a8d2c82fca
Create Date: 2026-09-16 15:34:41.120157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f56c8c8e86'
down_revision: Union[str, Sequence[str], None] = '86a8d2c82fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department_name')
    # ### end Alembic commands ###
