"""add_ai_columns

Revision ID: f5024d8a921f
Revises: f7d60419f2c6
Create Date: 2026-09-16 14:21:16.215832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5024d8a921f'
down_revision: Union[str, Sequence[str], None] = 'f7d60419f2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('ai_severity', sa.Integer(), nullable=True))
    op.add_column('cases', sa.Column('ai_intent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'ai_intent')
    op.drop_column('cases', 'ai_severity')
    # ### end Alembic commands ###
