"""Update agent task columns

Revision ID: f7d60419f2c6
Revises: d1b4a010c012
Create Date: 2026-09-15 15:07:40.870558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7d60419f2c6'
down_revision: Union[str, Sequence[str], None] = 'd1b4a010c012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_tasks', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agent_tasks', sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('agent_tasks', 'result_payload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_tasks', sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('agent_tasks', 'result_data')
    op.drop_column('agent_tasks', 'payload')
    # ### end Alembic commands ###
